print('hello'.upper())
print('GODDAMN'.lower())
s='Hello, World!'
print(s.upper())
print(s.lower())
print(s.count('o'))
print(s.count('o',8))
print(s.count('o',7))
print(s.count('l',1,3))
print(s.count('l',1,4))
print(s.find('e'))
print(s.find('wor'))
print(s.find('z'))
print(s.find('o'))
print(s.rfind('o'))
print(s.find('o',6))
print(s.index('o'))
print(s.rindex('o'))
print(s.replace('o','???'))
print(s.replace('l',''))
print(s.replace(' ',''))
print(s.replace('l','',2))
print(s.isalpha())
print('ygutrojk'.isalpha())
print('213124asf'.isalpha())
print('1234'.isdigit())
print('123 4'.isdigit())
print('111'.rjust(5,'0'))
print('111'.ljust(5,'0'))
w='Ivanov Ivan Ivanovich'
print(w.split())
print(len(w.split()))
print(w.split('n'))
h='650,756,65,24,198'
print(h)
t=h.split(',')
print(t)
print('='.join(t))
print('='.join(h))