import turtle as t
t.hideturtle()
t.pensize(5)
t.left(90)
t.color("red")

# t.forward(100)
# t.right(90)
# t.forward(50)
# t.right(180)
# t.forward(100)
# t.right(180)
# t.forward(50)
# t.right(90)
# t.forward(100)
# t.right(90)
# t.forward(50)
# t.right(180)
# t.forward(100)
# t.color("white")
# t.forward(60)
# t.color("black")
# t.left(90)
# t.forward(100)
# t.right(90)
# t.forward(50)
# t.right(180)
# t.forward(100)
# t.right(180)
# t.forward(50)
# t.right(90)
# t.forward(100)
# IT haribin shigariw












